package org.perfectjpattern.jee.integration.dao;

import org.eclipse.persistence.tools.schemaframework.*;

/**
 * This class was generated by the TopLink table creator generator.
 * It stores the meta-data (tables) that define the database schema.
 * @see oracle.toplink.tools.workbench.TableCreatorClassGenerator
 */
public 
class PersonTableCreator 
extends TableCreator 
{
    //------------------------------------------------------------------------
    // public
    //------------------------------------------------------------------------
    public 
    PersonTableCreator() 
    {
        setName("ExampleProject");
        
        addTableDefinition(buildPersonTable());
    }

    //------------------------------------------------------------------------
    public TableDefinition 
    buildPersonTable()
    {
        TableDefinition myTable = new TableDefinition();
        myTable.setName("PERSON_");
        
        FieldDefinition myFieldAge = new FieldDefinition();
        myFieldAge.setName("AGE");
        myFieldAge.setTypeName("INTEGER");
        myFieldAge.setSize(0);
        myFieldAge.setSubSize(0);
        myFieldAge.setIsPrimaryKey(false);
        myFieldAge.setIsIdentity(false);
        myFieldAge.setUnique(false);
        myFieldAge.setShouldAllowNull(false);
        myTable.addField(myFieldAge);
        
        FieldDefinition myFieldId = new FieldDefinition();
        myFieldId.setName("ID");
        myFieldId.setTypeName("NUMERIC");
        myFieldId.setSize(0);
        myFieldId.setSubSize(0);
        myFieldId.setIsPrimaryKey(true);
        myFieldId.setIsIdentity(false);
        myFieldId.setUnique(false);
        myFieldId.setShouldAllowNull(false);
        myTable.addField(myFieldId);
        
        FieldDefinition myFieldName = new FieldDefinition();
        myFieldName.setName("NAME");
        myFieldName.setTypeName("VARCHAR");
        myFieldName.setSize(25);
        myFieldName.setSubSize(0);
        myFieldName.setIsPrimaryKey(false);
        myFieldName.setIsIdentity(false);
        myFieldName.setUnique(false);
        myFieldName.setShouldAllowNull(false);
        myTable.addField(myFieldName);
        
        return myTable;
    }
}
